In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:/Users/USER/Desktop/URL-Phishing-Detection/datasets/clean_data_train.csv")

In [3]:
df.columns

Index(['LengthOfURL', 'DomainLengthOfURL', 'IsDomainIP', 'TLDLength',
       'URLLetterRatio', 'DigitCntInURL', 'EqualCharCntInURL',
       'QuesMarkCntInURL', 'OtherSpclCharCntInURL', 'HavingPath', 'PathLength',
       'HavingAnchor', 'HasSSL', 'IsUnreachable', 'LineOfCode', 'HasTitle',
       'HasFavicon', 'HasRobotsBlocked', 'IsResponsive', 'IsURLRedirects',
       'IsSelfRedirects', 'HasDescription', 'IsFormSubmitExternal',
       'HasSocialMediaPage', 'HasSubmitButton', 'HasHiddenFields',
       'HasPasswordFields', 'HasBankingKey', 'HasPaymentKey',
       'HasCopyrightInfoKey', 'CntImages', 'CntFilesCSS', 'CntFilesJS',
       'CntSelfHRef', 'CntEmptyRef', 'CntExternalRef', 'CntIFrame',
       'UniqueFeatureCnt', 'ShannonEntropy', 'FractalDimension',
       'KolmogorovComplexity', 'HexPatternCnt', 'Base64PatternCnt',
       'LikelinessIndex', 'Label'],
      dtype='object')

----------------URL VE SAYFA İÇERİĞİ ÖZELLİKLERİYLE -----------------------

In [4]:
x = df.drop("Label", axis=1)
y = df["Label"].values.ravel()

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB

from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import f1_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

b = BernoulliNB()
l = LogisticRegression(max_iter=1000)
d = DecisionTreeClassifier()
r = RandomForestClassifier()
gb= GradientBoostingClassifier()
kn= KNeighborsClassifier()
ab= AdaBoostClassifier()
mn= MultinomialNB()

def algo_test(x, y):
    modeller=[ b, l, d, r, gb, kn, ab, mn]
    isimler=["BernoulliNB", "LogisticRegression", "DecisionTreeClassifier", 
             "RandomForestClassifier", "GradientBoostingClassifier", "KNeighborsClassifier",
             "AdaBoostClassifier", "MultinomialNB"]

    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.3, random_state = 42)
    
    accuracy = []
    precision = []
    recall = []
    f1 = []
    mdl=[]

    print("Veriler hazır modeller deneniyor")
    for model in modeller:
        print(model, " modeli eğitiliyor!..")
        model=model.fit(x_train,y_train)
        tahmin=model.predict(x_test)
        mdl.append(model)
        accuracy.append(accuracy_score(y_test, tahmin))
        precision.append(precision_score(y_test, tahmin, average="micro"))
        recall.append(recall_score(y_test, tahmin, average="micro"))
        f1.append(f1_score(y_test, tahmin, average="micro"))
        print(confusion_matrix(y_test, tahmin))

    print("Eğitim tamamlandı.")
    
    metrics=pd.DataFrame(columns=["Accuracy", "Precision", "Recall", "F1", "Model"], index=isimler)
    metrics["Accuracy"] = accuracy
    metrics["Precision"] = precision  
    metrics["Recall"] = recall
    metrics["F1"] = f1
    metrics["Model"]=mdl

    metrics.sort_values("F1", ascending=False, inplace=True)

    print("En başarılı model: ", metrics.iloc[0].name)
    model=metrics.iloc[0,-1]
    tahmin=model.predict(np.array(x_test) if model==kn else x_test)
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, tahmin))
    print("classification Report:")
    print(classification_report(y_test, tahmin))
    print("Diğer Modeller:")
    
    return metrics.drop("Model", axis=1)

In [6]:
algo_test(x,y)

Veriler hazır modeller deneniyor
BernoulliNB()  modeli eğitiliyor!..
[[45914  2408]
 [  192 52509]]
LogisticRegression(max_iter=1000)  modeli eğitiliyor!..

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[[48078   244]
 [  367 52334]]
DecisionTreeClassifier()  modeli eğitiliyor!..
[[48266    56]
 [   39 52662]]
RandomForestClassifier()  modeli eğitiliyor!..
[[48290    32]
 [   66 52635]]
GradientBoostingClassifier()  modeli eğitiliyor!..
[[48280    42]
 [   54 52647]]
KNeighborsClassifier()  modeli eğitiliyor!..
[[47779   543]
 [  962 51739]]
AdaBoostClassifier()  modeli eğitiliyor!..
[[48146   176]
 [  137 52564]]
MultinomialNB()  modeli eğitiliyor!..
[[39528  8794]
 [ 1040 51661]]
Eğitim tamamlandı.
En başarılı model:  DecisionTreeClassifier
Confusion Matrix:
[[48266    56]
 [   39 52662]]
classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     48322
           1       1.00      1.00      1.00     52701

    accuracy                           1.00    101023
   macro avg       1.00      1.00      1.00    101023
weighted avg       1.00      1.00      1.00    101023

Diğer Modeller:

                            Accuracy  Precision    Recall        F1
DecisionTreeClassifier      0.999060   0.999060  0.999060  0.999060
GradientBoostingClassifier  0.999050   0.999050  0.999050  0.999050
RandomForestClassifier      0.999030   0.999030  0.999030  0.999030
AdaBoostClassifier          0.996902   0.996902  0.996902  0.996902
LogisticRegression          0.993952   0.993952  0.993952  0.993952
KNeighborsClassifier        0.985102   0.985102  0.985102  0.985102
BernoulliNB                 0.974263   0.974263  0.974263  0.974263
MultinomialNB               0.902656   0.902656  0.902656  0.902656

---------------- URL TABANLI ÖZELLİKLERLE EĞİTİM ALMA -----------------------

In [7]:
df = df[
    [
        # Uzunluk & Domain
        "LengthOfURL",
        "DomainLengthOfURL",
        "TLDLength",
        "IsDomainIP",

        # Karakter & Yapı
        "DigitCntInURL",
        "EqualCharCntInURL",
        "QuesMarkCntInURL",
        "OtherSpclCharCntInURL",
        "URLLetterRatio",
        "HavingPath",
        "HavingAnchor",
        "PathLength",

        # Matematiksel / Metin Karmaşıklığı
        "ShannonEntropy",
        "FractalDimension",
        "KolmogorovComplexity",
        "HexPatternCnt",
        "Base64PatternCnt",

        # Hedef
        "Label",
    ]
]

In [8]:
df.head(10)

,LengthOfURL,DomainLengthOfURL,TLDLength,IsDomainIP,DigitCntInURL,EqualCharCntInURL,QuesMarkCntInURL,OtherSpclCharCntInURL,URLLetterRatio,HavingPath,HavingAnchor,PathLength,ShannonEntropy,FractalDimension,KolmogorovComplexity,HexPatternCnt,Base64PatternCnt,Label
0,84,76,3,0,17,0,0,4,0.655,0,0,0,4.739567,1.00,1.000000,1,3,1
1,40,20,8,1,17,0,0,6,0.250,2,0,1,3.808271,1.00,1.222222,5,3,1
2,28,19,3,0,2,0,0,3,0.536,1,0,1,4.056021,0.75,1.307692,0,2,1
3,31,23,3,0,0,0,0,3,0.677,1,0,1,3.827833,0.75,1.275862,0,2,1
4,23,15,2,0,0,0,0,2,0.391,0,0,0,3.346439,1.00,1.400000,0,2,0
5,34,25,3,0,0,0,0,4,0.647,1,0,1,3.965018,0.75,1.250000,0,3,1
6,38,30,3,0,0,0,0,4,0.579,0,0,0,3.917626,1.00,1.235294,0,3,1
7,28,20,2,0,0,0,0,1,0.536,0,0,0,3.719295,1.00,1.307692,0,2,0
8,22,7,2,0,1,0,0,2,0.500,1,0,7,4.070656,1.00,1.380952,1,2,1
9,26,18,3,0,0,0,0,1,0.500,0,0,0,3.636842,1.00,1.333333,0,2,0

In [9]:
x = df.drop("Label", axis=1)
y = df["Label"].values.ravel()

In [10]:
x.head(10)

,LengthOfURL,DomainLengthOfURL,TLDLength,IsDomainIP,DigitCntInURL,EqualCharCntInURL,QuesMarkCntInURL,OtherSpclCharCntInURL,URLLetterRatio,HavingPath,HavingAnchor,PathLength,ShannonEntropy,FractalDimension,KolmogorovComplexity,HexPatternCnt,Base64PatternCnt
0,84,76,3,0,17,0,0,4,0.655,0,0,0,4.739567,1.00,1.000000,1,3
1,40,20,8,1,17,0,0,6,0.250,2,0,1,3.808271,1.00,1.222222,5,3
2,28,19,3,0,2,0,0,3,0.536,1,0,1,4.056021,0.75,1.307692,0,2
3,31,23,3,0,0,0,0,3,0.677,1,0,1,3.827833,0.75,1.275862,0,2
4,23,15,2,0,0,0,0,2,0.391,0,0,0,3.346439,1.00,1.400000,0,2
5,34,25,3,0,0,0,0,4,0.647,1,0,1,3.965018,0.75,1.250000,0,3
6,38,30,3,0,0,0,0,4,0.579,0,0,0,3.917626,1.00,1.235294,0,3
7,28,20,2,0,0,0,0,1,0.536,0,0,0,3.719295,1.00,1.307692,0,2
8,22,7,2,0,1,0,0,2,0.500,1,0,7,4.070656,1.00,1.380952,1,2
9,26,18,3,0,0,0,0,1,0.500,0,0,0,3.636842,1.00,1.333333,0,2

In [11]:
algo_test(x,y)

Veriler hazır modeller deneniyor
BernoulliNB()  modeli eğitiliyor!..
[[46100  2222]
 [ 7851 44850]]
LogisticRegression(max_iter=1000)  modeli eğitiliyor!..

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[[47972   350]
 [ 2613 50088]]
DecisionTreeClassifier()  modeli eğitiliyor!..
[[48160   162]
 [  291 52410]]
RandomForestClassifier()  modeli eğitiliyor!..
[[48223    99]
 [  252 52449]]
GradientBoostingClassifier()  modeli eğitiliyor!..
[[48060   262]
 [ 2127 50574]]
KNeighborsClassifier()  modeli eğitiliyor!..
[[48187   135]
 [  450 52251]]
AdaBoostClassifier()  modeli eğitiliyor!..
[[48050   272]
 [ 6815 45886]]
MultinomialNB()  modeli eğitiliyor!..
[[48202   120]
 [14967 37734]]
Eğitim tamamlandı.
En başarılı model:  RandomForestClassifier
Confusion Matrix:
[[48223    99]
 [  252 52449]]
classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      1.00     48322
           1       1.00      1.00      1.00     52701

    accuracy                           1.00    101023
   macro avg       1.00      1.00      1.00    101023
weighted avg       1.00      1.00      1.00    101023

Diğer Modeller:

                            Accuracy  Precision    Recall        F1
RandomForestClassifier      0.996526   0.996526  0.996526  0.996526
DecisionTreeClassifier      0.995516   0.995516  0.995516  0.995516
KNeighborsClassifier        0.994209   0.994209  0.994209  0.994209
GradientBoostingClassifier  0.976352   0.976352  0.976352  0.976352
LogisticRegression          0.970670   0.970670  0.970670  0.970670
AdaBoostClassifier          0.929848   0.929848  0.929848  0.929848
BernoulliNB                 0.900290   0.900290  0.900290  0.900290
MultinomialNB               0.850658   0.850658  0.850658  0.850658

In [12]:
# modelin doğruluğu hangi özelliğe daha çok bağlı olduğunu görmek için . Modele etkisini 
gb.fit(x, y)
importances = pd.Series(gb.feature_importances_, index=x.columns)
print(importances.sort_values(ascending=False).head(10))

PathLength               0.745107
URLLetterRatio           0.056937
DigitCntInURL            0.052964
OtherSpclCharCntInURL    0.050152
DomainLengthOfURL        0.028836
LengthOfURL              0.018704
TLDLength                0.018535
KolmogorovComplexity     0.014744
HavingPath               0.005973
HavingAnchor             0.005209
dtype: float64

In [15]:
# PathLength çıkarıldıktan sonra modelin doğruluk oranındaki değişiklik
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import GradientBoostingClassifier

# PathLength çıkar
x_test2 = x.drop("PathLength", axis=1)

scores = cross_val_score(
    GradientBoostingClassifier(),
    x_test2,
    y,
    cv=5,
    scoring="f1"
)

print(scores)
print("Ortalama:", scores.mean())

[0.97681465 0.97358676 0.97809819 0.97682879 0.97690055]
Ortalama: 0.9764457877621757

In [ ]:
# PathLength ÖNEMLİ BİR ÖZELLİK ANCAK ÇIKARILDIĞINDA MODELİN DOĞRULUĞU ÇOK DÜŞMEDİĞİ İÇİN DİĞER ÖZELLİKLERDE SONUÇTA ETKİLİ